name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Action Release
      # You may pin to the exact commit or the version.
      # uses: yakuhzi/release-asset@f96c41c3fdc53a02ab20a60014725490f91702a3
      uses: yakuhzi/release-asset@v1.2.3
      with:
        # File to upload to the release
        file: "/release"
